/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Artemis;

import Artemis.Controllers.LoginController;
import javafx.application.Application;
import javafx.stage.Stage;
import org.apache.commons.logging.Log;

public class App extends Application{

    private String accessToken;

    public static void main(String[] args){

        launch(args);

        LoginController loginController = new LoginController();
        loginController.main(args);
        loginController.setAccessToken(loginController.getAccessToken());
        System.out.println(loginController.getAccessToken());


    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

    }
}
