/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Artemis;

import Artemis.Controllers.LoginController;
import Artemis.Controllers.StudentDashboard;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application{


    public static void main(String[] args){


        launch(args);

    }



    @Override
    public void start(Stage primaryStage) throws Exception {

        FXMLLoader loader = new FXMLLoader(getClass().getResource("/LoginView.fxml"));
        Parent root = loader.load();
        Scene loginScene = new Scene(root);
        primaryStage.setScene(loginScene);
        primaryStage.show();

    }


}
