/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Artemis;

import Artemis.Views.LoginView;
import Artemis.Views.StudentDashboard;

public class App {

    public static void main(String[] args) {

        LoginView.main(args);


    }
}
